---
title: "Modeling isotopes"
output: html_notebook
---

```{r}
d<-read.csv("Froehle.csv")
```
```{r}
library(ggplot2)
g<-ggplot(d, aes(x=diet, y=apatite))
g+geom_point()
```
Creating a linear model with confidence intervals around the line, and predicted values. 


```{r}
m<-lm(data=d, apatite~diet)
h_hat<-predict(m, newdata=data.frame(diet=d$diet))
df<-data.frame(cbind(d$diet, d$apatite, h_hat))
names(df)<-c("diet", "ap", "yhat")
head(df)
```

```{r}
g <- ggplot(data = df, aes(x = diet, y = yhat))
g <- g + geom_point()
g <- g + geom_point(aes(x = diet, y = ap), colour = "red")
g <- g + geom_segment(aes(x = diet, y = yhat, xend = diet, yend = ap))
g
```

```{r}
ci <- predict(m, newdata = data.frame(diet = d$diet), interval = "confidence", 
    level = 0.95)  # for a vector of values
head(ci)
```

```{r}
df <- cbind(df, ci)
names(df) <- c("diet", "ap", "yhat", "CIfit", "CIlwr", "CIupr")
head(df)
```

```{r}
x<-df$diet
y<-df$ap
g <- ggplot(data = df, aes(x = x, y = y))
g <- g + geom_point(alpha = 1/2)
g <- g + geom_line(aes(x = x, y = CIfit), colour = "black")
g <- g + geom_line(aes(x = x, y = CIlwr), colour = "blue")
g <- g + geom_line(aes(x = x, y = CIupr), colour = "blue")
g
```

```{r}
pi <- predict(m, newdata = data.frame(diet = d$diet), interval = "prediction", 
    level = 0.95)  # for a vector of values
head(pi)
```

```{r}
df <- cbind(df, pi)
names(df) <- c("diet", "ap", "yhat", "CIfit", "CIlwr", "CIupr", "PIfit", "PIlwr", 
    "PIupr")
head(df)
```

```{r}
g <- g + geom_line(data = df, aes(x = diet, y = PIlwr), colour = "red")
g <- g + geom_line(data = df, aes(x = diet, y = PIupr), colour = "red")
g
```
```{r}
summary(m)
```
# Code i can use to predict apatite from whole diet values with confidence interval
```{r}
pi <- predict(m, newdata = data.frame(diet = -14), interval = "prediction", 
    level = 0.95)  # for a single value
pi
```

#I can use the opposite of this equation to estimate the total diet based on apatite.




```{r}
m<-lm(data=d,diet~apatite)
h_hat<-predict(m, newdata=data.frame(apatite=d$apatite))
df<-data.frame(cbind(d$apatite, d$diet, h_hat))
names(df)<-c("ap", "diet", "yhat")
head(df)
```

```{r}
g <- ggplot(data = df, aes(x = ap, y = yhat))
g <- g + geom_point()
g <- g + geom_point(aes(x = ap, y = diet), colour = "red")
g <- g + geom_segment(aes(x = ap, y = yhat, xend = ap, yend = diet))
g
```

```{r}
ci <- predict(m, newdata = data.frame(apatite = d$apatite), interval = "confidence", 
    level = 0.95)  # for a vector of values
head(ci)
```

```{r}
df <- cbind(df, ci)
names(df) <- c("ap", "diet", "yhat", "CIfit", "CIlwr", "CIupr")
head(df)
```

```{r}
x<-df$ap
y<-df$diet
g <- ggplot(data = df, aes(x = x, y = y))
g <- g + geom_point(alpha = 1/2)
g <- g + geom_line(aes(x = x, y = CIfit), colour = "black")
g <- g + geom_line(aes(x = x, y = CIlwr), colour = "blue")
g <- g + geom_line(aes(x = x, y = CIupr), colour = "blue")
g
```

```{r}
pi <- predict(m, newdata = data.frame(apatite = d$ap), interval = "prediction", 
    level = 0.95)  # for a vector of values
head(pi)
```

```{r}
df <- cbind(df, pi)
names(df) <- c("ap", "diet", "yhat", "CIfit", "CIlwr", "CIupr", "PIfit", "PIlwr", 
    "PIupr")
head(df)
```

```{r}
g <- g + geom_line(data = df, aes(x = ap, y = PIlwr), colour = "red")
g <- g + geom_line(data = df, aes(x = ap, y = PIupr), colour = "red")
g
```

Predicting total diet from apatite results from Manzanilla 2012 book. 

```{r}
pi <- predict(m, newdata = data.frame(apatite = c(-3.48, -2.23, -9.42, -1.86, -0.79, -7.57, -8.47)), interval = "prediction", 
    level = 0.95)  # for a single value
pi
```

```{r}
df <- cbind((data.frame(apatite = c(-3.48, -2.23, -9.42, -1.86, -0.79, -7.57, -8.47))), pi)
names(df)<-c("ap", "model", "lwr", "upr")
df
```



```{r}
g <- ggplot(data = df, aes(x = ap, y = model))
g <- g + geom_line(aes(x = ap, y = model))
g <- g + geom_point(aes(color="3"))
g <- g + geom_segment(aes(x = ap, y = upr, xend = ap, yend = lwr))
g + geom_line(aes(y=-16, color="agricultural"))+geom_line(aes(y=-24, color="Lacustrine"))+geom_line(aes(y=-20, color="mount/forest"))+geom_line(aes(y=-13, color="C4_100%"))
```


With grimstead data
```{r}
grim<-data.frame(apatite=c(-10.6, -10.8, -10.2, -12.4, -10.8, -11.4, -10.7, -11.2, -9.7, -9.5, -8.3, -9.4, -10.8, -10.1, -12.5, -12.6, -11.8, -12.7, -12.8, -10.7, -7.7, -9.7, -10.3, -10.6, -10.5, -10.2, -9.2, -11.0, -10.0, -7.5, -6.0, -4.7, -5.8, -3.8))

pi2 <- predict(m, newdata = grim, interval = "prediction", 
    level = 0.95)  # for a single value
pi2

df2 <- cbind(data.frame(grim, pi2))
names(df2)<-c("ap", "model", "lwr", "upr")
df2
```


```{r}
g <- ggplot(data = df2, aes(x = ap, y = model))
g <- g + geom_line(aes(x = ap, y = model))
g <- g + geom_point(aes(color="3"))
g <- g + geom_segment(aes(x = ap, y = upr, xend = ap, yend = lwr))
g + geom_line(aes(y=-16, color="agricultural"))+geom_line(aes(y=-24, color="Lacustrine"))+geom_line(aes(y=-20, color="mount/forest"))+geom_line(aes(y=-13, color="C4_100%"))
```


